FROM ubuntu:22.04

# NOTE: We do a silly dance here: wabt doesn't provide aarch64 binaries, and
#       we'd like to provide multiarch images. We install wasmtime and use their
#       WASI build of wasm2c :)

# # install wasmtime
# RUN apt-get update && apt-get install -y wget curl tar xz-utils && \
#     curl https://wasmtime.dev/install.sh -sSf | bash
# 
# # install wabt's wasi version (we need ~1.0.34)
# RUN wget -nv https://github.com/WebAssembly/wabt/releases/download/1.0.34/wabt-1.0.34-wasi.tar.gz && \
#     mkdir /wabt && \
#     tar -kxzf wabt-1.0.34-wasi.tar.gz --strip-components 1 -C /wabt/ && \
#     rm wabt-1.0.34-wasi.tar.gz


# install up-to-date wabt (we need ~1.0.31)
# TODO: support aarch64
RUN apt-get update && apt-get install -y wget tar xz-utils && \
    wget -nv https://github.com/WebAssembly/wabt/releases/download/1.0.31/wabt-1.0.31-ubuntu.tar.gz && \
    tar -kxzf wabt-1.0.31-ubuntu.tar.gz --strip-components 1 -C /usr/

# install wizer for wasm2c pre-init
RUN wget -nv "https://github.com/bytecodealliance/wizer/releases/download/v3.0.1/wizer-v3.0.1-`uname -m`-linux.tar.xz" && \
    tar xf wizer-v3.0.1-`uname -m`-linux.tar.xz \
        -C /usr/bin/ --strip-components 1 \
        wizer-v3.0.1-`uname -m`-linux/wizer && \
    rm wizer-v3.0.1-`uname -m`-linux.tar.xz

WORKDIR /
COPY prepare-wasm2c-fuzzer.sh /usr/bin/
COPY wasm2c-wrapper.c /
RUN chmod +x /usr/bin/prepare-wasm2c-fuzzer.sh
