FROM wasm-fuzzers-wasm2c-base
RUN apt-get install -y build-essential curl git pkg-config libssl-dev
RUN git clone https://github.com/fuzzm/fuzzm-project

RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN apt-get update && apt-get install -y llvm llvm-dev clang

WORKDIR /fuzzm-project/wasm_instrumenter
RUN sed -i 's/wasabi"/wasabi", rev="519da3ced4e1ae11daeea39f3588bb89643bb7bb"/' Cargo.toml 
RUN cargo update && cargo install --path .

WORKDIR /fuzzm-project
RUN wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-11/wasi-sdk-11.0-linux.tar.gz && \
    tar xvf wasi-sdk-11.0-linux.tar.gz
RUN cd AFL-wasm && make install

COPY fuzzm.sh /usr/bin/fuzzm.sh
RUN chmod +x /usr/bin/fuzzm.sh
WORKDIR /
ENTRYPOINT [ "fuzzm.sh" ]
