FROM ubuntu:22.04

RUN apt-get update && apt-get install -y git cmake clang wget curl tar xz-utils

RUN git clone https://github.com/turbolent/w2c2 && cd w2c2 && \
    cmake -B build && cmake --build build

# install wizer for w2c2 pre-init
RUN wget -nv "https://github.com/bytecodealliance/wizer/releases/download/v3.0.1/wizer-v3.0.1-`uname -m`-linux.tar.xz" && \
    tar xf wizer-v3.0.1-`uname -m`-linux.tar.xz \
        -C /usr/bin/ --strip-components 1 \
        wizer-v3.0.1-`uname -m`-linux/wizer && \
    rm wizer-v3.0.1-`uname -m`-linux.tar.xz

WORKDIR /
COPY prepare-w2c2-fuzzer.sh /usr/bin/
COPY w2c2-wrapper.c /
RUN chmod +x /usr/bin/prepare-w2c2-fuzzer.sh
