# ubuntu:24.04 is rustc 1.75
# ubuntu:24.10 is rustc 1.80
# libafl needs 1.82 for `&raw const GLOBAL_MUT`

FROM ubuntu:24.04
RUN apt-get update && apt-get install -y rustup git clang
RUN rustup toolchain add 1.82 --no-self-update
RUN git clone https://github.com/CISPA-SysSec/wasmfuzz && git -C wasmfuzz checkout ac17ec0ce7cfd7d5988cf6bb76418b3219def4fe
RUN cargo install --no-default-features --path /wasmfuzz && ln -s /root/.cargo/bin/wasmfuzz /usr/bin/
COPY wasmfuzz.sh /usr/bin/
RUN chmod +x /usr/bin/wasmfuzz.sh
RUN mkdir -p /seeds/ && echo -n "YELLOW SUBMARINE" > /seeds/seed && mkdir -p /corpus/
ENTRYPOINT [ "wasmfuzz.sh" ]
