FROM wasm-fuzzers-wasm2c-base
RUN apt-get update && apt-get install -y clang
COPY libfuzzer-wasm2c.sh /usr/bin/libfuzzer-wasm2c.sh
RUN chmod +x /usr/bin/libfuzzer-wasm2c.sh
ENTRYPOINT [ "libfuzzer-wasm2c.sh" ]
