FROM wasm-fuzzers-wasm2c-base

RUN apt-get update && apt-get install -y wget software-properties-common
RUN apt-get install -y \
    autoconf \
    automake \
    build-essential \
    cmake \
    libtool \
    llvm llvm-dev clang \
    make \
    ninja-build \
    sudo \
    unzip \
    zlib1g-dev \
    patchelf \
    libzstd-dev \
    git sed rsync

# install wafl
# RUN git clone https://github.com/fgsect/WAFL
RUN git clone https://github.com/Mrmaxmeier/WAFL
WORKDIR /WAFL
RUN git checkout fix-symbol-overlap && git submodule update --init && \
    git submodule update --recursive --remote

# Compile and install AFL++
WORKDIR /WAFL/AFLplusplus
RUN make WAFL_MODE=1 TEST_MMAP=1 install
# RUN make install
# TODO: wafl expects AFLplusplus instrumentation passes at /AFLplusplus/x-pass.so
RUN ln -s /WAFL/AFLplusplus /

# Compile and install the WAVM part
WORKDIR /WAFL/build
RUN cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo
RUN ninja && ninja install && \
    patchelf --add-needed /usr/local/lib/libWAVM.so /usr/local/bin/wavm

WORKDIR /
COPY wafl.sh shim-for-wafl.sh run-afl-fuzz.sh /usr/bin/
RUN chmod +x /usr/bin/wafl.sh /usr/bin/shim-for-wafl.sh /usr/bin/run-afl-fuzz.sh
RUN mkdir -p /seeds/ && echo -n "YELLOW SUBMARINE" > /seeds/seed && mkdir -p /corpus/
ENTRYPOINT [ "wafl.sh" ]
