FROM ubuntu:24.04 AS builder
RUN apt-get update && apt-get install -y rustup git clang
RUN rustup toolchain add 1.86 --no-self-update
ARG COMMIT="9f904255398d1006427091953ea9746f7134b9dd"
RUN git clone https://github.com/CISPA-SysSec/wasmfuzz && git -C wasmfuzz checkout "$COMMIT"
RUN cargo install --locked --no-default-features --path /wasmfuzz

FROM ubuntu:24.04
COPY --from=builder /root/.cargo/bin/wasmfuzz /usr/bin/
COPY wasmfuzz.sh /usr/bin/
RUN chmod +x /usr/bin/wasmfuzz.sh
RUN mkdir -p /seeds/ && echo -n "YELLOW SUBMARINE" > /seeds/seed && mkdir -p /corpus/
ENTRYPOINT [ "wasmfuzz.sh" ]
