FROM ubuntu:24.04
RUN apt-get update && apt-get install -y wget
ARG RELEASE="initial-commit"
RUN wget -nv "https://github.com/CISPA-SysSec/wasmfuzz/releases/download/$RELEASE/wasmfuzz-`uname -m`-unknown-linux-gnu.2.31" -O /usr/bin/wasmfuzz && chmod +x /usr/bin/wasmfuzz
COPY wasmfuzz.sh /usr/bin/
RUN chmod +x /usr/bin/wasmfuzz.sh
RUN mkdir -p /seeds/ && echo -n "YELLOW SUBMARINE" > /seeds/seed && mkdir -p /corpus/
ENTRYPOINT [ "wasmfuzz.sh" ]
