set -e
git clone-rev.sh https://github.com/tirr-c/jxl-oxide.git "$PROJECT/repo" c0cc4c7ea57c1207f38ff2970d94757470613be4
git -C "$PROJECT/repo" apply ../limit-jbr-decode-resources.patch
git -C "$PROJECT/repo" apply ../port-wasi-render-wait-no-trace.patch
git -C "$PROJECT/repo" apply ../fix-dct-common-mutex-reentrancy.patch
git -C "$PROJECT/repo" apply ../port-tracing-release-max-level-off.patch
git -C "$PROJECT/repo" apply ../port-wasi-composite-drop-render-lock.patch
git -C "$PROJECT/repo" apply ../fix-blend-subgrid-bounds.patch
git -C "$PROJECT/repo" apply ../fix-blend-single-region-bounds.patch
git -C "$PROJECT/repo" apply ../fix-blend-empty-region.patch
git -C "$PROJECT/repo" apply ../fix-suggested-hdr-tf-missing-icc.patch
git -C "$PROJECT/repo" apply ../fix-adaptive-lf-smoothing-buffer-len.patch
git -C "$PROJECT/repo" apply ../fix-subgrid-range-saturating.patch
git -C "$PROJECT/repo" apply ../fix-gabor-region-bounds.patch
git -C "$PROJECT/repo" apply ../fix-upsample-jpeg-grayscale.patch
git -C "$PROJECT/repo" apply ../fix-modular-pass-shift-lookup.patch
git -C "$PROJECT/repo" apply ../fix-hlg-transfer-grayscale.patch
git -C "$PROJECT/repo" apply ../fix-blend-color-channel-mismatch.patch
git -C "$PROJECT/repo" apply ../fix-epf-region-contains.patch
git -C "$PROJECT/repo" apply ../fix-spline-point-count-overflow.patch
git -C "$PROJECT/repo" apply ../fix-xyb-transform-soft-fail.patch
git -C "$PROJECT/repo" apply ../fix-toc-offset-overflow.patch
git -C "$PROJECT/repo" apply ../fix-blend-alpha-region-bounds.patch
git -C "$PROJECT/repo" apply ../fix-toc-permutation-index-bounds.patch
git -C "$PROJECT/repo" apply ../fix-alloc-tracker-size-overflow.patch
git -C "$PROJECT/repo" apply ../fix-grid-dimension-overflow.patch
git -C "$PROJECT/repo" apply ../fix-patch-ref-channel-mismatch.patch
git -C "$PROJECT/repo" apply ../fix-icc-tag-table-overflow.patch
git -C "$PROJECT/repo" apply ../fix-patch-empty-ref-grid.patch
git -C "$PROJECT/repo" apply ../fix-vardct-modular-region-block-aligned.patch
git -C "$PROJECT/repo" apply ../fix-ma-table-bound-overflow.patch
