set -e
git clone-rev.sh https://github.com/etemesi254/zune-image "$PROJECT/repo" 2fa0e4176cc6f99d241032f50afb3428aa84b078
git -C "$PROJECT/repo" apply "$PROJECT/fuzz-disable-idct.patch"
git -C "$PROJECT/repo" apply "$PROJECT/fuzz-png-roundtrip-api.patch"
git -C "$PROJECT/repo" apply "$PROJECT/fix-zcursor-read-overflow.patch"
git -C "$PROJECT/repo" apply "$PROJECT/limit-hdr-output-size.patch"
git -C "$PROJECT/repo" apply "$PROJECT/fix-ppm-header-overflow.patch"
git -C "$PROJECT/repo" apply "$PROJECT/limit-psd-output-size.patch"
git -C "$PROJECT/repo" apply "$PROJECT/limit-qoi-output-size.patch"
git -C "$PROJECT/repo" apply "$PROJECT/limit-png-output-size.patch"
git -C "$PROJECT/repo" apply "$PROJECT/limit-bmp-output-size.patch"
git -C "$PROJECT/repo" apply "$PROJECT/fix-jpeg-mcu-upsampling-bounds.patch"
git -C "$PROJECT/repo" apply "$PROJECT/fix-jpeg-worker-upsampling-bounds.patch"
git -C "$PROJECT/repo" apply "$PROJECT/limit-jpeg-output-size.patch"
git -C "$PROJECT/repo" apply "$PROJECT/fuzz-decode-incremental-wasm-cap.patch"
